# ----
# Site

title: "Tablero de control"
url: "https://pelos6.github.io/tableroDeControl"
baseurl:
google_analytics_key:
show_full_navigation: true

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /siteicon.png
description: Documentación de un intento de tablero de control de todas las aplicaciónes que llevo en el curro
author:
  name: javier
  email:
  twitter: # twitter username without the @ symbol
social:
  name: Edition Template
  links:
    - https://github.com/CloudCannon/edition-jekyll-template

# -----
# Build

permalink: pretty

# intento que funcione como el renderizado de codigo en GFM
# pero no lo soporta github pages
# pygments: true


gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

collections:
  docs:
    title: Documentation
    permalink: /:path/
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      layout: default
  -
    scope:
      path: ""
      type: "docs"
    values:
      seo:
        type: Article
      _comments:
        category: Group navigation links with this field
        order: Used to sort links in the navigation
  -
    scope:
      path: ""
      type: "posts"
    values:
      _comments:
        type: Marks the impact of this release

# -----------
# CloudCannon

types:
  - minor
  - major
